---20210217--------------------------------------------------------------
SELECT * FROM(
SELECT DEPTNO,MAX(SAL) MS
FROM EMP
GROUP BY DEPTNO)
WHERE MS>=3000;

SELECT * FROM EMP
WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);


-- 다중행, 다중열
-- PAIRWISE
SELECT *
FROM EMP
WHERE (SAL,NVL(COMM,0)) IN (SELECT SAL,NVL(COMM,0)
        FROM EMP
        WHERE DEPTNO=30);

-- UNPAIRWISE
SELECT *
FROM EMP
WHERE SAL IN(SELECT SAL
            FROM EMP
            WHERE DEPTNO=30)
AND
    NVL(COMM,0) IN (SELECT NVL(COMM,0)
                    FROM EMP
                    WHERE DEPTNO=30);

-------------------------------------------------------------------------
-- 1. 학생중에서 성이 '이'씨인 학생이름,사용자 아이디,학과번호,학과이름,교수이름을 출력하여라
SELECT S.NAME STUDENT,S.USERID,S.DEPTNO DEPTNO,D.DNAME DEPTNAME,P.POSITION POSITION,P.NAME PROFESSOR
FROM STUDENT S, DEPARTMENT D, PROFESSOR P
WHERE S.NAME LIKE '이%' AND S.DEPTNO=D.DEPTNO AND S.DEPTNO=P.DEPTNO;

SELECT S.NAME STUDENT,S.USERID,S.DEPTNO DEPTNO,D.DNAME DEPTNAME,P.NAME PROFESSOR
FROM (SELECT * FROM STUDENT WHERE NAME LIKE '이%') S, DEPARTMENT D, (SELECT * FROM PROFESSOR WHERE POSITION='교수') P
WHERE S.DEPTNO=D.DEPTNO AND D.DEPTNO=P.DEPTNO AND S.DEPTNO=P.DEPTNO;

-- 2. 소속 교수는 있으나 소속 학생이 없는 학과 번호를 출력하여라.
SELECT DEPTNO
FROM PROFESSOR P,DEPARTMENT D,STUDENT S
WHERE P.DEPTNO=D.DEPTNO;

-- 3. 보직수당을 받지 않는 교수의 이름, 급여, 학과 번호,학과이름,연봉 등급을 출력하여라.
SELECT P.NAME,P.SAL,P.DEPTNO,D.DNAME,S.GRADE
FROM(
SELECT *
FROM PROFESSOR WHERE COMM IS NULL) P, DEPARTMENT D, SALGRADE S
WHERE P.DEPTNO=D.DEPTNO;

SELECT NAME,SAL,
FROM PROFESSOR, SALGRADE S
CASE SAL WHEN S.LOSAL BETWEEN S.HISAL THEN 1,
        WHEN S.LOSAL BETWEEN S.HISAL THEN 2
 
SELECT * FROM STUDENT;
SELECT * FROM DEPARTMENT;
SELECT * FROM PROFESSOR;
SELECT * FROM SALGRADE;