--20210224
SELECT * FROM TAB;

SELECT SUM(SAL) OVER()
FROM EMP;

SELECT * FROM JDBCTABLE;

DROP TABLE JDBCBBS;
CREATE TABLE JDBCBBS(
NO NUMBER(5) CONSTRAINT JDBCBBS_NO PRIMARY KEY,
TITLE VARCHAR2(20),
WRITER VARCHAR2(20),
CONTENTS CLOB,
PASSWORD VARCHAR2(10),
HIT NUMBER(5),
REGDATE DATE);

SELECT * FROM JDBCBBS;

DROP SEQUENCE JDBCBBS_SEQ;
CREATE SEQUENCE JDBCBBS_SEQ;

SELECT * FROM JDBCBBS;

SELECT * FROM EMP;

SELECT * FROM DEPT;


